version: '3.8'

services:
  url-shortener:  # Nombre del servicio
    build: .      # Construye la imagen usando el Dockerfile
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del host al 3000 del contenedor
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app      
      - /app/node_modules  # Evita sobrescribir node_modules
    restart: unless-stopped  # Reinicia si falla