# Usa una imagen oficial de Node.js
FROM node:18-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias primero (para aprovechar caché de Docker)
COPY package.json .

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos
COPY . .

# Puerto expuesto (debe coincidir con el de tu app, en este caso 3000)
EXPOSE 3000

# Comando para iniciar la app
CMD ["node", "server.js"]