version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: mc1122
    ports:
      - "25565:25565"
    environment:
      ENABLE_RCON: "true"
      RCON_PASSWORD: "miclavercon"
      RCON_PORT: 25575
      EULA: "TRUE"
      VERSION: "1.20.6"
      ONLINE_MODE: "FALSE"     # Permite que se conecten jugadores sin cuenta premium
      MEMORY: "2G"
    volumes:
      - ./data:/data
    restart: unless-stopped
