FROM python:3.11-slim

WORKDIR /app

# Instala dependencias críticas
RUN apt-get update && \
    apt-get install -y \
    libpam0g \
    libpam-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 5000
CMD ["python", "app.py"]